LINE_OBJECT_LENGTH = 10
GRAVITY_CONSTANT = 8
SEEKED_JUMP_HEIGHT = 170
TRANSITION_FRAMES = 1
DINO_SIZE = 0.7
PLAYER_JUMP_SPEED = 20

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Dinosaur runner"
UP, DOWN = 'U', 'D'
ACTIONS = [UP, DOWN]

PREFIX_RESSOURCE = "resources/"

DEFAULT_LEARNING_RATE = 1
DEFAULT_DISCOUNT_FACTOR = 0.5

REWARD_STUCK = -6
REWARD_DEFAULT = 1