LINE_OBJECT_LENGTH = 10
GRAVITY_CONSTANT = 8
SEEKED_JUMP_HEIGHT = 170
TRANSITION_FRAMES = 1
TRANSITION_FRAMES_LAY_DOWN=4
DINO_SIZE = 0.7
PLAYER_JUMP_SPEED = 20

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Dinosaur runner"
UP, DOWN, WALK = 'U', 'D', 'W'
ACTIONS = [WALK, DOWN, UP]

PREFIX_RESSOURCE = "resources/"

DEFAULT_LEARNING_RATE = 1
DEFAULT_DISCOUNT_FACTOR = 0.5

REWARD_STUCK = -200
REWARD_DOWN = -25
REWARD_UP = -50
REWARD_DEFAULT = -1
